import Head from 'next/head'
import Image from 'next/image'
import Nav from './navbar'
import Footer from './footer'
import exampleImg from '../public/pexels-photo-1929659.jpeg'
import { Input, Button } from "@material-tailwind/react"
import { useEffect, useRef, useState } from 'react'
import { useSpring } from 'react-spring'

export default function Home() {
  
  const rowElement = useRef()

  useEffect(()=> {
    const handleScroll = event => {
      console.log(window.scrollY)
      const rows = document.getElementsByName('row')
      console.log(rows)
    }
    window.addEventListener('scroll', handleScroll)

    return () => {
      window.removeEventListener('scroll', handleScroll)
    }
  }, [])

  return (
    <>
    <div className='relative'>
      <Head>
        <title>myapp10</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
        <div className='w-full grid grid-cols-12 justify-items-center h-96' style={{transform: 'translateY(100px)'}}>
          <div className='w-full col-span-1 bg-blue-gray-600'></div>
          <div className='w-full col-span-10 bg-blue-gray-200'></div>
          <div className='w-full col-span-1 bg-blue-gray-600'></div>
        </div>
      <div id='row' className='w-full grid grid-cols-10 justify-items-center h-96' style={{transform: 'translateY(100px)'}}>
        {/* <div className='w-full col-span-1 bg-blue-gray-600'></div> */}
        <div className='w-full col-span-10 bg-blue-gray-200'></div>
        {/* <div className='w-full col-span-1 bg-blue-gray-600'></div> */}
      </div>
      <Image
        src={exampleImg}
        alt='iamg'
        width={1717}
        height={2576}
        ></Image>
      <Footer/>
    </div>
    </>
  )
}
