import Nav from './navbar'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { Button, Card, CardBody, CardFooter, CardHeader, Typography } from "@material-tailwind/react"



export default function Store () {
  
  const [dndData, setDndData] = useState([])

    const fetchBooks = async () => {
      const response = await fetch('https://www.dnd5eapi.co/api/monsters/')
      const data = await response.json()
      setDndData(data.results)
      console.log(data)
    }
  
  const externaImageLoader = ({ src }: { src: string }) =>
    `${src}`;

  return (
    <div>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <Button onClick={fetchBooks}> Get books </Button>
      <div className='grid grid-cols-3 grid-flow-row justify-items-center'>
        {dndData.map(monster => {
          return (
              <Card key={monster.index} className='w-80 m-2'>
                <CardHeader className='p-2 mt-4'>
                  {/* <Image
                  unoptimized
                  loader={externaImageLoader}
                  alt={book.title}
                  src={book.cover}
                  width={100}
                  height={100}
                  className='w-auto h-auto p-2'
                ></Image> */}
                  <Typography>
                    Title: {monster.name}
                  </Typography>
                </CardHeader>
                <CardBody className='text-center'>
                  <Typography>
                    Title: {monster.url}
                  </Typography>
                </CardBody>
                <CardFooter>
                  <Typography>Add to cart</Typography>
                </CardFooter>
              </Card>
          )
        })}
      </div>
        
    </div>
  )
}